//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colaboradores
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADORES
    {
        public int IDCOLABORADOR { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public string GRADOACADEMICO { get; set; }
        public string DIRECCION { get; set; }
    }
}
